service: serverless-todos
frameworkVersion: "2 || 3"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  lambdaHashingVersion: "20201221"

functions:
  addTodo:
    handler: src/functions/addTodo.handle
    events:
      - http:
          path: /todos/{id}
          method: POST
          cors: true
  getTodo:
    handler: src/functions/getTodo.handle
    events:
      - http:
          path: /todos/{id}
          method: GET
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S

        GlobalSecondaryIndexes:
          - IndexName: index_user_id
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
